{% set name = "aisuite" %}
{% set version = "0.1.9" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aisuite-{{ version }}.tar.gz
  sha256: e0eb31e91b9899b86e620afa0f49b97cda24b44958ce53b2a06c24812eb3fe55

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - httpx >=0.27.0,<0.28.0
  run_constrained:
    - anthropic >=0.30.1,<0.31.0
    - boto3 >=1.34.144,<2.0.0
    - cohere >=5.12.0,<6.0.0
    - vertexai >=1.63.0,<2.0.0
    - groq >=0.9.0,<0.10.0
    - mistralai >=1.0.3,<2.0.0
    - openai >=1.35.8,<2.0.0
    - ibm-watsonx-ai >=1.1.16,<2.0.0

test:
  imports:
    - aisuite
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/andrewyng/aisuite
  summary: Uniform access layer for LLMs
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
